### PR TITLE
bugfix: fix dfget panic when crossWrite is true

### LINKED ISSUE #1410: dfget panic when use it to download file in p2p pattern.
### Ⅰ. Issue Description
l use the below command to download file in p2p pattern.
```
./dfget -u http://172.16.17.24:8000/go1.12.9.linux-amd64.tar.gz -o /root/go1.12.9.linux-amd64.tar.gz --home "/data/docker/.small-dragonfly"  --pattern p2p -s
 800MB --totallimit 800MB --node 172.16.17.24:8002,172.16.17.24:8002 --verbose
```

dfget panic info:
```
dfget version:
workspace:/data/docker/.small-dragonfly
sign:28934-1593952426.364
client:172.16.17.24 connected to node:172.16.17.24:8002
start download by dragonfly...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x94c8d3]

goroutine 39 [running]:
github.com/dragonflyoss/Dragonfly/dfget/core/downloader/p2p_downloader.(*Piece).RawContent(0xc00050a080, 0xc000826400, 0x0)
        /data/app/src/github.com/dragonflyoss/Dragonfly/dfget/core/downloader/p2p_downloader/piece.go:67 +0x33
github.com/dragonflyoss/Dragonfly/dfget/core/downloader/p2p_downloader.writePieceToFile(0xc00050a080, 0xc000826488, 0xc0005c3a70, 0x9, 0x5, 0x9d4eee)
        /data/app/src/github.com/dragonflyoss/Dragonfly/dfget/core/downloader/p2p_downloader/client_writer.go:248 +0x109
github.com/dragonflyoss/Dragonfly/dfget/core/downloader/p2p_downloader.(*TargetWriter).write(...)
        /data/app/src/github.com/dragonflyoss/Dragonfly/dfget/core/downloader/p2p_downloader/target_writer.go:125
github.com/dragonflyoss/Dragonfly/dfget/core/downloader/p2p_downloader.(*TargetWriter).Run(0xc000330620, 0xbcefe0, 0xc0000c5b00)
        /data/app/src/github.com/dragonflyoss/Dragonfly/dfget/core/downloader/p2p_downloader/target_writer.go:102 +0xf5
created by github.com/dragonflyoss/Dragonfly/dfget/core/downloader/p2p_downloader.(*ClientWriter).Run
        /data/app/src/github.com/dragonflyoss/Dragonfly/dfget/core/downloader/p2p_downloader/client_writer.go:166 +0x64
```

### Ⅱ. Describe what happened
dfget command panic

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
when the output file path(`--output`) and home directory(`--home`) are mounted under different disk device, p2p download process will panic.

### Ⅵ. Environment:

- dragonfly version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by zcc35357949**
Signed-off-by: zhouchencheng <zhouchencheng@bilibili.com>

### Ⅰ. Describe what this PR did
when  dfget's `--output` and `--home`  directories are mounted under different disk device, it makes the hard link between them fails to create. At that time, `crossWrite` will be true.

And the same piece will be written to different files twice. Currently the `autoreset` field in piece is always true, so the piece buffer will reset after the first written, then the second written will trigger panic.

### Ⅱ. Does this pull request fix one issue?
fixes #1410

### CODE REVIEW

File: dfget/core/downloader/p2p_downloader/piece.go [hunk 1]
```diff
@@ -57,20 +58,15 @@ type Piece struct {
...
 }
 
 // RawContent returns raw contents,
 // If the piece has wrapper, and the piece content will remove the head and tail.
 func (p *Piece) RawContent(noWrapper bool) *bytes.Buffer {
 	contents := p.Content.Bytes()
 	length := len(contents)
-	defer func() {
-		if p.autoReset {
-			p.ResetContent()
```
Comment (lowzj) [inline dfget/core/downloader/p2p_downloader/piece.go:71]: Why not invoke `TryResetContent` here to automatically release buffer?

Comment (zcc35357949) [reply dfget/core/downloader/p2p_downloader/piece.go:71]: > Why not invoke `TryResetContent` here to automatically release buffer?

we should release the buffer after the io.Copy() finishes, otherwise the same buffer may be reused for writing at the same time.  #1415

Comment (lowzj) [reply dfget/core/downloader/p2p_downloader/piece.go:71]: How to provide a method `WriteTo` in `piece` struct to write the raw content to writer and then release the buffer if necessary, just like :
```
n, e := piece.WriteTo(writer, noWrapper)
```

File: dfget/core/downloader/p2p_downloader/client_writer.go [hunk 2]
```diff
@@ -220,6 +221,7 @@ func (cw *ClientWriter) write(piece *Piece) error {
 	}
 
 	if cw.acrossWrite {
+		atomic.AddInt32(&piece.writerNum, 1)
```
Comment (lowzj) [inline dfget/core/downloader/p2p_downloader/client_writer.go:224]: It's better to abstract this line as a method of struct `Piece`, such as `Piece.IncWriter`.

File: dfget/core/downloader/p2p_downloader/piece.go (hunk 1 above)
Comment (zcc35357949) [reply dfget/core/downloader/p2p_downloader/piece.go:71]: that's a good idea,I will try it.

File: dfget/core/downloader/p2p_downloader/piece.go [hunk 3]
```diff
@@ -57,20 +60,36 @@ type Piece struct {
...
+	contents := p.Content.Bytes()
+	length := len(contents)
+	defer p.TryResetContent()
+
+	if noWrapper {
+		return bytes.NewBuffer(contents[:]).WriteTo(w)
+	}
+	if length >= 5 {
+		return bytes.NewBuffer(contents[4 : length-1]).WriteTo(w)
+	}
```
Comment (lowzj) [inline dfget/core/downloader/p2p_downloader/piece.go:79]: Here could reuse `p.RawContent(noWrapper)` to get buffer.

**Comment by lowzj** [comment]
please rebase your code from master to solve the CI problem
