### PR TITLE
bugfix:gc peer failing to server down

### LINKED ISSUE #886: [bug] when peer sever down fails,the gc progress can't gc the peer
### Ⅱ. Describe what happened
if   peer  download finish and send server down fails,the gc progress can't gc the peer.although the blanklist can mark the peer ,but can't gc it.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- dragonfly version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by yunfeiyanggzq**
Signed-off-by: yunfeiyangbuaa <yunfeiyang@buaa.edu.cn>

### Ⅱ. Does this pull request fix one issue?

fixes #886 
### Ⅳ. Describe how to verify it
 set  
```
func (s *Server) reportServiceDown(ctx context.Context, rw http.ResponseWriter, req *http.Request) (err error) {
	return nil
	params := req.URL.Query()
	taskID := params.Get("taskId")
	cID := params.Get("cid")

	// get peerID according to the CID and taskID
	dfgetTask, err := s.DfgetTaskMgr.Get(ctx, cID, taskID)
	if err != nil {
		return err
	}
	s.ProgressMgr.UpdatePeerServiceDown(ctx, dfgetTask.PeerID)

	return EncodeResponse(rw, http.StatusOK, &types.ResultInfo{
		Code: constants.CodeGetPeerDown,
	})
}

```
to make server down fail,and start some dfgets.wait some minutes and long  at the supernode log to see gc result
```
dstPID(buaa-127.0.0.1-1568789107329775876) pieceNum(0) pieceStatus(1)
2019-09-18 14:45:23.087 DEBU sign:15332 : success to update ClientProgress taskID(9627226867cf6d8496944de44f554b8d0d2e743c991da21ad3e05336f01e5ba9) srcCID(127.0.0.1-17109-1568789123.075) dstPID(buaa-127.0.0.1-1568789107329775876) pieceNum(0) pieceStatus(-3) with result: false
2019-09-18 14:45:23.087 DEBU sign:15332 : taskID(9627226867cf6d8496944de44f554b8d0d2e743c991da21ad3e05336f01e5ba9) clientID(127.0.0.1-17109-1568789123.075) get successful pieces: [0]
2019-09-18 14:47:02.217 INFO sign:15332 : gc tasks: success to full gc task count(0), remainder count(1)
2019-09-18 14:47:02.217 INFO sign:15332 : gc peers: success to gc peer count(0), remainder count(17)
2019-09-18 14:49:02.217 INFO sign:15332 : start to gc task: 9627226867cf6d8496944de44f554b8d0d2e743c991da21ad3e05336f01e5ba9
2019-09-18 14:49:02.217 INFO sign:15332 : gc peers: success to gc peer count(0), remainder count(17)
2019-09-18 14:49:02.217 INFO sign:15332 : gc tasks: success to full gc task count(1), remainder count(0)
2019-09-18 14:51:02.216 INFO sign:15332 : gc tasks: success to full gc task count(0), remainder count(0)
2019-09-18 14:51:02.216 INFO sign:15332 : gc peers: success to gc peer count(0), remainder count(17)
2019-09-18 14:53:02.217 INFO sign:15332 : gc tasks: success to full gc task count(0), remainder count(0)
2019-09-18 14:53:02.217 INFO sign:15332 : start to gc peer: buaa-127.0.0.1-1568789110215189714
2019-09-18 14:53:02.217 INFO sign:15332 : start to gc peer: buaa-127.0.0.1-1568789111710620517
2019-09-18 14:53:02.217 INFO sign:15332 : start to gc peer: buaa-127.0.0.1-1568789102503455620
2019-09-18 14:53:02.218 INFO sign:15332 : start to gc peer: buaa-127.0.0.1-1568789104356430736
2019-09-18 14:53:02.218 INFO sign:15332 : start to gc peer: buaa-127.0.0.1-1568789121686022462
2019-09-18 14:53:02.218 INFO sign:15332 : start to gc peer: buaa-127.0.0.1-1568789108759479973
2019-09-18 14:53:02.218 INFO sign:15332 : start to gc peer: buaa-127.0.0.1-1568789117378592819
2019-09-18 14:53:02.218 INFO sign:15332 : start to gc peer: buaa-127.0.0.1-1568789105879446327
2019-09-18 14:53:02.218 INFO sign:15332 : start to gc peer: buaa-127.0.0.1-1568789099644459405
2019-09-18 14:53:02.219 INFO sign:15332 : start to gc peer: buaa-127.0.0.1-1568789113174107121
2019-09-18 14:53:02.219 INFO sign:15332 : start to gc peer: buaa-127.0.0.1-1568789114643691712
2019-09-18 14:53:02.219 INFO sign:15332 : start to gc peer: buaa-127.0.0.1-1568789116020640445
2019-09-18 14:53:02.219 INFO sign:15332 : start to gc peer: buaa-127.0.0.1-1568789107329775876
2019-09-18 14:53:02.219 INFO sign:15332 : start to gc peer: buaa-127.0.0.1-1568789118858206450
2019-09-18 14:53:02.219 INFO sign:15332 : start to gc peer: buaa-127.0.0.1-1568789120304483555
2019-09-18 14:53:02.219 INFO sign:15332 : start to gc peer: buaa-127.0.0.1-1568789123076779584
2019-09-18 14:53:02.219 INFO sign:15332 : gc peers: success to gc peer count(16), remainder count(1)
```

### CODE REVIEW

**Comment by yunfeiyanggzq** [comment]
Done  @Starnop

File: supernode/daemon/mgr/scheduler/manager.go [hunk 1]
```diff
@@ -228,6 +231,26 @@ func (sm *Manager) tryGetPID(ctx context.Context, taskID string, pieceNum int, s
...
+		if isExistInMap(blackInfo, peerIDs[i]) {
+			// if the peer is in blank list and dfgetTask finishes(this peer may be off without report server down successfully), server down time by supernode.
+			cid, err := sm.dfgetTask.GetCIDByPeerIDAndTaskID(ctx, peerIDs[i], taskID)
+			if err != nil {
+				logrus.Warnf("failed to get cID by peerID %s and TaskID %s, err: %v", peerIDs[i], taskID, err)
+				continue
+			}
+			dfgetTask, err := sm.dfgetTask.Get(ctx, cid, taskID)
+			if err == nil && dfgetTask.Status == types.DfGetTaskStatusSUCCESS {
+				sm.progressMgr.UpdatePeerServiceDown(ctx, peerIDs[i])
```
Comment (Starnop) [inline supernode/daemon/mgr/scheduler/manager.go]: Firstly, we should understand the relationship between peer and dfgetTask. In fact, one peer  corresponds to multi dfgetTasks. So  we should also confirm if any other dfgetTask is running before we  judge a peer might go offline.

Comment (yunfeiyanggzq) [reply supernode/daemon/mgr/scheduler/manager.go]: oh,I ignore that,I will do with it

Comment (yunfeiyanggzq) [reply supernode/daemon/mgr/scheduler/manager.go]: if a peer is off when dowenload,the dfgetTask will be unfinished,how we judge it?

Comment (yunfeiyanggzq) [reply supernode/daemon/mgr/scheduler/manager.go]: I mean a peer which crashes  will have some dead dfgetTask,it hard to judge it ,can you have some good idea.

Comment (Starnop) [reply supernode/daemon/mgr/scheduler/manager.go]: If a dfgetTask has not been updated for a long time with running state, and then we shall think this task has failed. WDYT? @yunfeiyanggzq @lowzj

Comment (yunfeiyanggzq) [reply supernode/daemon/mgr/scheduler/manager.go]: have we recorded the  latest dfget access time in Dragonfly?if not ,do you think we need to add the time

Comment (Starnop) [reply supernode/daemon/mgr/scheduler/manager.go]: In fact, we have not recorded the latest dfget access time. And that's exactly what  we should do.

**Comment by yunfeiyanggzq** [comment]
I  understand.I will fix it in this way

**Comment by yunfeiyanggzq** [comment]
@Starnop   Done

File: supernode/daemon/mgr/gc/gc_dfget_task.go [hunk 2]
```diff
@@ -25,6 +25,16 @@ import (
...
+		// TODO:now pid and cid correspond one-to-one,so we can delete a pid by cid. but in future,our dragonfly api will make pid and cid one to many,so we can't delete a pid by cid.
+		// TODO:in future we may add heartbeat between dfget and supernode.so we will implement it in other way.
+		dfgetTask, err := gcm.dfgetTaskMgr.Get(ctx, cid, taskID)
+		if err != nil {
+			errSlice = append(errSlice, errors.Wrapf(err, "failed to get dfgetTask by cid(%s)", cid))
+			continue
+		}
+		gcm.progressMgr.UpdatePeerServiceDown(ctx, dfgetTask.PeerID)
+
 		if err := gcm.progressMgr.DeleteCID(ctx, cid); err != nil {
```
Comment (Starnop) [inline supernode/daemon/mgr/gc/gc_dfget_task.go]: We should exec the delete cid operation even if failed to get the dfgetTask info.

File: supernode/daemon/mgr/gc/gc_dfget_task.go [hunk 3]
```diff
@@ -25,6 +25,16 @@ import (
 func (gcm *Manager) gcDfgetTasksWithTaskID(ctx context.Context, taskID string, cids []string) []error {
 	var errSlice []error
 	for _, cid := range cids {
+		// these peers may crashes that haven't report sever down.
+		// TODO:now pid and cid correspond one-to-one,so we can delete a pid by cid. but in future,our dragonfly api will make pid and cid one to many,so we can't delete a pid by cid.
```
Comment (Starnop) [inline supernode/daemon/mgr/gc/gc_dfget_task.go]: split this sentence into two or more lines. THX.

File: supernode/daemon/mgr/gc/gc_peer.go [hunk 4]
```diff
@@ -38,6 +38,10 @@ func (gcm *Manager) gcPeers(ctx context.Context) {
 		peerState, err := gcm.progressMgr.GetPeerStateByPeerID(ctx, peerID)
 		if err != nil {
 			logrus.Warnf("gc peers: failed to get peerState peerID(%s): %v", peerID, err)
+			if !gcm.gcPeer(ctx, peerID) {
+				logrus.Warnf("gc peers: failed to gc peer peerID(%s) after failing to get peerState: %v", peerID, err)
+				continue
```
Comment (Starnop) [inline supernode/daemon/mgr/gc/gc_peer.go]: redundant `continue`

Comment (yunfeiyanggzq) [reply supernode/daemon/mgr/gc/gc_peer.go]: > redundant `continue`

Done @Starnop

File: supernode/daemon/mgr/gc/gc_dfget_task.go (hunk 2 above)
Comment (yunfeiyanggzq) [reply supernode/daemon/mgr/gc/gc_dfget_task.go]: > We should exec the delete cid operation even if failed to get the dfgetTask info.

Done

**Comment by Starnop** [comment]
LGTM. 

And also cc/ @lowzj. PTAL. THX.
