### PR TITLE
bugfix: modify two supernode api's bug

### LINKED ISSUE #680: [bug]dfget's supernode API return err
### Ⅰ. Issue Description
the two [dfget's supernode api](https://github.com/dragonflyoss/Dragonfly/blob/21d2390907a870c2fa51c9d721ca464127c379b5/dfget/core/api/supernode_api.go#L98) will return a json parsing error，but the coder ignores it.
```
func (api *supernodeAPI) ServiceDown(node string, taskID string, cid string) (
	resp *types.BaseResponse, e error) {
func (api *supernodeAPI) ReportPiece(node string, req *types.ReportPieceRequest) (
	resp *types.BaseResponse, e error) {
```
so when dfget[ use these api](https://github.com/dragonflyoss/Dragonfly/blob/21d2390907a870c2fa51c9d721ca464127c379b5/dfget/core/downloader/p2p_downloader/client_writer.go#L198),it ignore the error
```
cw.api.ReportPiece(piece.SuperNode, &types.ReportPieceRequest{
		TaskID:     piece.TaskID,
		Cid:        cw.cfg.RV.Cid,
		DstCid:     piece.DstCid,
		PieceRange: piece.Range,
})
if cost.Seconds() > 2.0 {
		logrus.Infof(
		"async writer and report suc from dst:%s... cost:%.3f for range:%s",
		piece.DstCid[:25], cost.Seconds(), piece.Range)
 }

if ok {
	ps.api.ServiceDown(task.superNode, task.taskID, task.cid)
	serviceFile := helper.GetServiceFile(key.(string), task.dataDir)
	os.Remove(serviceFile)
	logrus.Infof("shutdown, remove task id:%s file:%s",
	task.taskID, serviceFile)
}
```
### Ⅱ. Describe what happened
error happen but we haven't do with it

### Ⅲ. Describe what you expected to happen

when we use these api,we can do with the error
### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- dragonfly version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by yunfeiyangbuaa**
Signed-off-by: yunfeiyangbuaa <yunfeiyang@buaa.edu.cn>

### Ⅰ. Describe what this PR did

- First bug:when supernode send  response to dfget's reportpiece and servicedown request,it will return a nil response.So when the dfget do with the response with `json.Unmarshal(body, resp)` ,it will produce an `err unexpected end of JSON input` err.I add a status code info to the supernode's response to resolve these bugs and do with the err and status code
- Second bug:when dfget send pulltask request to supernode.if the supernode is off,the dfget will crash instead of find another supernode to finish its work.because the pulltask will retuen a `{}` instead of `nil`,the coder use `nil` to check the res,so it will happen `a invalid memory address or nil pointer dereference ` err .i make the return be nil when the supernode is off

### Ⅱ. Does this pull request fix one issue?

fixes #680

### Ⅳ. Describe how to verify it
you can add a fmt.println() to the previous code's api return err,it will report an err.and my code won't

### CODE REVIEW

**Comment by allencloud** [comment]
Please carefully check the CI failures. Thanks a lot. @yunfeiyangbuaa

**Comment by yunfeiyangbuaa** [comment]
> Please carefully check the CI failures. Thanks a lot. @yunfeiyangbuaa

Done

File: dfget/core/downloader/p2p_downloader/client_writer.go [hunk 1]
```diff
@@ -196,12 +197,18 @@ func startSyncWriter(queue util.Queue) util.Queue {
...
 func (cw *ClientWriter) sendSuccessPiece(piece *Piece, cost time.Duration) {
-	cw.api.ReportPiece(piece.SuperNode, &types.ReportPieceRequest{
+	resp, e := cw.api.ReportPiece(piece.SuperNode, &types.ReportPieceRequest{
 		TaskID:     piece.TaskID,
 		Cid:        cw.cfg.RV.Cid,
 		DstCid:     piece.DstCid,
 		PieceRange: piece.Range,
 	})
+	if e != nil {
+		logrus.Errorf("sendSuccessPiece error:%v", e)
```
Comment (allencloud) [inline dfget/core/downloader/p2p_downloader/client_writer.go]: `logrus.Errorf("failed to report piece: %v", err)`
Please see https://github.com/alibaba/pouch/blob/master/docs/contributions/code_styles.md#rule005---generation-of-action-failure

In addition, you should add a white space between `:` and the detailed error message.

File: dfget/core/downloader/p2p_downloader/client_writer.go [hunk 2]
```diff
@@ -196,12 +197,18 @@ func startSyncWriter(queue util.Queue) util.Queue {
...
+	}
+	if resp.Code != constants.CodeGetPieceReport {
+		logrus.Errorf("send success piece report to supernode failed")
```
Comment (allencloud) [inline dfget/core/downloader/p2p_downloader/client_writer.go]: logrus.Errorf("failed to report piece to supernode: api response code is %d not equal to %d, resp.Code, constants.CodeGetPieceReport")

When we are reporting an error to one user, we should provide as many details as possible. Only by that can user get more accurate information of the actual state. @yunfeiyangbuaa 
And it will reduce more effort you paid in debugging.

File: dfget/core/uploader/peer_server.go [hunk 3]
```diff
@@ -457,7 +458,13 @@ func (ps *peerServer) shutdown() {
 	ps.syncTaskMap.Range(func(key, value interface{}) bool {
 		task, ok := value.(*taskConfig)
 		if ok {
-			ps.api.ServiceDown(task.superNode, task.taskID, task.cid)
+			resp, e := ps.api.ServiceDown(task.superNode, task.taskID, task.cid)
+			if e != nil {
+				logrus.Errorf("send ServiceDown error:%v", e)
```
Comment (allencloud) [inline dfget/core/uploader/peer_server.go]: Same issue here, please see the above comments. Thanks.

File: dfget/core/downloader/p2p_downloader/client_writer.go [hunk 4]
```diff
@@ -196,12 +197,18 @@ func startSyncWriter(queue util.Queue) util.Queue {
...
+	resp, e := cw.api.ReportPiece(piece.SuperNode, &types.ReportPieceRequest{
 		TaskID:     piece.TaskID,
 		Cid:        cw.cfg.RV.Cid,
 		DstCid:     piece.DstCid,
 		PieceRange: piece.Range,
 	})
+	if e != nil {
+		logrus.Errorf("sendSuccessPiece error:%v", e)
+	}
+	if resp.Code != constants.CodeGetPieceReport {
```
Comment (allencloud) [inline dfget/core/downloader/p2p_downloader/client_writer.go]: I think here should be in an `else` block. 

```
if e := nil {
    logrus.Errorf("failed to report piece: %v", err)
} else if resp.Code != constants.CodeGetPieceReport {
    logrus.Errorf("send success piece report to supernode failed")
}
```

File: dfget/core/downloader/p2p_downloader/client_writer.go (hunk 2 above)
Comment (yunfeiyangbuaa) [reply dfget/core/downloader/p2p_downloader/client_writer.go]: Done

File: dfget/core/downloader/p2p_downloader/client_writer.go (hunk 1 above)
Comment (yunfeiyangbuaa) [reply dfget/core/downloader/p2p_downloader/client_writer.go]: Done

File: dfget/core/uploader/peer_server.go (hunk 3 above)
Comment (yunfeiyangbuaa) [reply dfget/core/uploader/peer_server.go]: Done

File: dfget/core/downloader/p2p_downloader/client_writer.go (hunk 4 above)
Comment (yunfeiyangbuaa) [reply dfget/core/downloader/p2p_downloader/client_writer.go]: Done

File: dfget/core/downloader/p2p_downloader/client_writer.go [hunk 5]
```diff
@@ -196,12 +197,17 @@ func startSyncWriter(queue util.Queue) util.Queue {
 }
 
 func (cw *ClientWriter) sendSuccessPiece(piece *Piece, cost time.Duration) {
-	cw.api.ReportPiece(piece.SuperNode, &types.ReportPieceRequest{
+	resp, e := cw.api.ReportPiece(piece.SuperNode, &types.ReportPieceRequest{
```
Comment (Starnop) [inline dfget/core/downloader/p2p_downloader/client_writer.go]: I think we should add a `info` log here. Just make a record.

File: dfget/core/uploader/peer_server.go [hunk 6]
```diff
@@ -457,7 +458,12 @@ func (ps *peerServer) shutdown() {
 	ps.syncTaskMap.Range(func(key, value interface{}) bool {
 		task, ok := value.(*taskConfig)
 		if ok {
-			ps.api.ServiceDown(task.superNode, task.taskID, task.cid)
+			resp, e := ps.api.ServiceDown(task.superNode, task.taskID, task.cid)
+			if e != nil {
```
Comment (Starnop) [inline dfget/core/uploader/peer_server.go]: I am wondering if it is more appropriate to handle errors in the api functions? And then we can reduce redundant code for error handling. WDYT?

File: dfget/core/uploader/peer_server.go [hunk 7]
```diff
@@ -457,7 +458,12 @@ func (ps *peerServer) shutdown() {
...
+				logrus.Errorf("failed to send service down: %v", e)
```
Comment (Starnop) [inline dfget/core/uploader/peer_server.go]: We should record the info about task to make it more valuable.

File: dfget/core/api/supernode_api.go [hunk 8]
```diff
@@ -100,9 +103,13 @@ func (api *supernodeAPI) ReportPiece(node string, req *types.ReportPieceRequest)
 
 	url := fmt.Sprintf("%s://%s%s?%s",
 		api.Scheme, node, peerReportPiecePath, util.ParseQuery(req))
-
 	resp = new(types.BaseResponse)
 	e = api.get(url, resp)
+	if e != nil {
+		logrus.Infof("failed to report piece{taskid:%s,range:%s},err: %v", req.TaskID, req.PieceRange, e)
+	} else if resp != nil && resp.Code != constants.CodeGetPieceReport {
```
Comment (Starnop) [inline dfget/core/api/supernode_api.go]: We should record the info about **resp** to make it more valuable.

Comment (yunfeiyangbuaa) [reply dfget/core/api/supernode_api.go]: but I have put the resp.code into log already.

Comment (yunfeiyangbuaa) [reply dfget/core/api/supernode_api.go]: > We should record the info about **resp** to make it more valuable.
but I have put the resp.code into log already.

Comment (yunfeiyangbuaa) [reply dfget/core/api/supernode_api.go]: but I have put the resp.code into log already.

File: dfget/core/api/supernode_api.go [hunk 9]
```diff
@@ -90,7 +93,9 @@ func (api *supernodeAPI) PullPieceTask(node string, req *types.PullPieceTaskRequ
 		api.Scheme, node, peerPullPieceTaskPath, util.ParseQuery(req))
 
 	resp = new(types.PullPieceTaskResponse)
-	e = api.get(url, resp)
+	if e = api.get(url, resp); e != nil {
```
Comment (allencloud) [inline dfget/core/api/supernode_api.go]: Why to change this? I do not see any difference after the change actually.

Comment (yunfeiyangbuaa) [reply dfget/core/api/supernode_api.go]: https://github.com/dragonflyoss/Dragonfly/blob/c5d08731c856c3f71d09eb0a0dc7567754f7a0ed/dfget/core/downloader/p2p_downloader/p2p_downloader.go#L240

File: dfget/core/api/supernode_api.go [hunk 10]
```diff
@@ -100,9 +105,14 @@ func (api *supernodeAPI) ReportPiece(node string, req *types.ReportPieceRequest)
 
 	url := fmt.Sprintf("%s://%s%s?%s",
 		api.Scheme, node, peerReportPiecePath, util.ParseQuery(req))
-
 	resp = new(types.BaseResponse)
 	e = api.get(url, resp)
+	if e != nil {
+		logrus.Infof("failed to report piece{taskid:%s,range:%s},err: %v", req.TaskID, req.PieceRange, e)
```
Comment (allencloud) [inline dfget/core/api/supernode_api.go]: Please confirm that here is an `Infof` level log, or `Errorf` level log?

File: dfget/core/api/supernode_api.go (hunk 9 above)
Comment (yunfeiyangbuaa) [reply dfget/core/api/supernode_api.go]: if the supernode is off,the resp={} in the previous code.and res.code will make the dfget happen a `a invalid memory address or nil pointer dereference` err

File: dfget/core/api/supernode_api.go (hunk 8 above)
Comment (allencloud) [reply dfget/core/api/supernode_api.go]: If there is a `return` of the if block, there is no need to add `else`. The following is better:
```
if e != nil {
    logrus.Errorf("blabla")
    return nil, e
}

if resp != nil && resp.Code != constants.CodeGetPieceReport {
    
}
```

File: dfget/core/api/supernode_api.go [hunk 11]
```diff
@@ -115,6 +125,12 @@ func (api *supernodeAPI) ServiceDown(node string, taskID string, cid string) (
 
 	resp = new(types.BaseResponse)
 	e = api.get(url, resp)
+	if e != nil {
+		logrus.Infof("failed to send service down,err: %v", e)
+		return nil, e
+	} else if resp != nil && resp.Code != constants.CodeGetPeerDown {
```
Comment (allencloud) [inline dfget/core/api/supernode_api.go]: reduce the `else` please, like the above.

File: dfget/core/api/supernode_api.go [hunk 12]
```diff
@@ -100,9 +105,14 @@ func (api *supernodeAPI) ReportPiece(node string, req *types.ReportPieceRequest)
...
 	url := fmt.Sprintf("%s://%s%s?%s",
 		api.Scheme, node, peerReportPiecePath, util.ParseQuery(req))
-
 	resp = new(types.BaseResponse)
 	e = api.get(url, resp)
+	if e != nil {
+		logrus.Infof("failed to report piece{taskid:%s,range:%s},err: %v", req.TaskID, req.PieceRange, e)
+		return nil, e
+	} else if resp != nil && resp.Code != constants.CodeGetPieceReport {
+		logrus.Infof("failed to report piece{taskid:%s,range:%s} to supernode: api response code is %d not equal to %d", req.TaskID, req.PieceRange, resp.Code, constants.CodeGetPieceReport)
```
Comment (allencloud) [inline dfget/core/api/supernode_api.go]: please check the log level.

File: dfget/core/api/supernode_api.go [hunk 13]
```diff
@@ -115,6 +125,12 @@ func (api *supernodeAPI) ServiceDown(node string, taskID string, cid string) (
 
 	resp = new(types.BaseResponse)
 	e = api.get(url, resp)
+	if e != nil {
+		logrus.Infof("failed to send service down,err: %v", e)
```
Comment (allencloud) [inline dfget/core/api/supernode_api.go]: please check the log level.

File: dfget/core/api/supernode_api.go (hunk 9 above)
Comment (yunfeiyangbuaa) [reply dfget/core/api/supernode_api.go]: I return a nil if the supernode if off so the the program will  go on

File: dfget/core/api/supernode_api.go (hunk 10 above)
Comment (yunfeiyangbuaa) [reply dfget/core/api/supernode_api.go]: https://github.com/dragonflyoss/Dragonfly/pull/682#discussion_r305192168

File: dfget/core/api/supernode_api.go (hunk 9 above)
Comment (allencloud) [reply dfget/core/api/supernode_api.go]: It is so tricky. I would like to see you change the function definition. Please do not define the variables in the function declaration. Just define them in the implementation block.

File: dfget/core/api/supernode_api.go (hunk 10 above)
Comment (yunfeiyangbuaa) [reply dfget/core/api/supernode_api.go]: @Starnop https://github.com/dragonflyoss/Dragonfly/pull/682#discussion_r305192168
Error or Info ?

Comment (allencloud) [reply dfget/core/api/supernode_api.go]: I am sure that `Info` level is improper. Both `Error` and `Warn` are better.

File: dfget/core/api/supernode_api.go (hunk 9 above)
Comment (yunfeiyangbuaa) [reply dfget/core/api/supernode_api.go]: > It is so tricky. I would like to see you change the function definition. Please do not define the variables in the function declaration. Just define them in the implementation block.
In fact I can't understand your  comment very clearly,Can in more details?.But I think the coder want to return a nil when a err happen such as https://github.com/dragonflyoss/Dragonfly/blob/c5d08731c856c3f71d09eb0a0dc7567754f7a0ed/dfget/core/api/supernode_api.go#L73.
and he just ignore this place in the previous implement .

File: dfget/core/api/supernode_api.go (hunk 10 above)
Comment (yunfeiyangbuaa) [reply dfget/core/api/supernode_api.go]: > I am sure that `Info` level is improper. Both `Error` and `Warn` are better.
I am agree with you.I will modify it

File: dfget/core/api/supernode_api.go (hunk 9 above)
Comment (yunfeiyangbuaa) [reply dfget/core/api/supernode_api.go]: > It is so tricky. I would like to see you change the function definition. Please do not define the variables in the function declaration. Just define them in the implementation block.
In fact I can't understand your  comment very clearly,Can in more details?.But I think the coder want to return a nil when a err happen such as https://github.com/dragonflyoss/Dragonfly/blob/c5d08731c856c3f71d09eb0a0dc7567754f7a0ed/dfget/core/api/supernode_api.go#L73.
and he just ignore this place in the previous implement .

File: dfget/core/api/supernode_api.go (hunk 8 above)
Comment (yunfeiyangbuaa) [reply dfget/core/api/supernode_api.go]: Done

File: dfget/core/api/supernode_api.go (hunk 10 above)
Comment (yunfeiyangbuaa) [reply dfget/core/api/supernode_api.go]: Done

File: dfget/core/api/supernode_api.go (hunk 11 above)
Comment (yunfeiyangbuaa) [reply dfget/core/api/supernode_api.go]: Done

File: dfget/core/api/supernode_api.go (hunk 13 above)
Comment (yunfeiyangbuaa) [reply dfget/core/api/supernode_api.go]: Done

File: dfget/core/api/supernode_api.go [hunk 14]
```diff
@@ -100,9 +105,15 @@ func (api *supernodeAPI) ReportPiece(node string, req *types.ReportPieceRequest)
 
 	url := fmt.Sprintf("%s://%s%s?%s",
 		api.Scheme, node, peerReportPiecePath, util.ParseQuery(req))
-
 	resp = new(types.BaseResponse)
 	e = api.get(url, resp)
```
Comment (Starnop) [inline dfget/core/api/supernode_api.go]:
```
	if e := api.get(url, resp);e != nil {
		logrus.Errorf("failed to report piece{taskid:%s,range:%s},err: %v", req.TaskID, req.PieceRange, e)
		return nil, e
	}
```

File: dfget/core/api/supernode_api.go [hunk 15]
```diff
@@ -115,6 +126,13 @@ func (api *supernodeAPI) ServiceDown(node string, taskID string, cid string) (
 
 	resp = new(types.BaseResponse)
 	e = api.get(url, resp)
```
Comment (Starnop) [inline dfget/core/api/supernode_api.go]: So do with the above.

File: dfget/core/api/supernode_api.go (hunk 14 above)
Comment (yunfeiyangbuaa) [reply dfget/core/api/supernode_api.go]: Done

File: dfget/core/api/supernode_api.go (hunk 15 above)
Comment (yunfeiyangbuaa) [reply dfget/core/api/supernode_api.go]: Done

**Comment by yunfeiyangbuaa** [comment]
> Method `Register` also need to be fixed.

done

**Comment by Starnop** [comment]
LGTM.

**Comment by yunfeiyangbuaa** [comment]
> LGTM. @yunfeiyangbuaa And could you please make a rebase?

Done

File: dfget/core/api/supernode_api.go [hunk 16]
```diff
@@ -100,9 +107,14 @@ func (api *supernodeAPI) ReportPiece(node string, req *types.ReportPieceRequest)
 
 	url := fmt.Sprintf("%s://%s%s?%s",
 		api.Scheme, node, peerReportPiecePath, util.ParseQuery(req))
-
 	resp = new(types.BaseResponse)
-	e = api.get(url, resp)
+	if e = api.get(url, resp); e != nil {
+		logrus.Errorf("failed to report piece{taskid:%s,range:%s},err: %v", req.TaskID, req.PieceRange, e)
```
Comment (lowzj) [inline dfget/core/api/supernode_api.go]: Just return `error` in API implementation rather than logging them. Then the caller can choose to log the error themselves.

Comment (yunfeiyangbuaa) [reply dfget/core/api/supernode_api.go]: dfgte haven't check all the err and response.so should I and a check ?  @lowzj

Comment (yunfeiyangbuaa) [reply dfget/core/api/supernode_api.go]: https://github.com/dragonflyoss/Dragonfly/pull/682#discussion_r305193116 
I added a check before. and I think it is a good idea to add checks in supernode api

**Comment by Starnop** [comment]
LGTM.
